# -*- coding: utf-8 -*-
"""Funçso reduce.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nSlr1a0XfX75ah4DhV2DOyGzN9G2CYA1
"""

from dados import produtos, pessoas, lista
from functools import reduce
soma_idades = reduce(lambda ac, p: ac + p['idade'],pessoas, 0)
print(soma_idades / len(pessoas))