# -*- coding: utf-8 -*-
"""Função filter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WPVCpSbHBynPs_IpcUN3T3XWIr2M6t0E
"""

from dados import produtos, pessoas, lista

def filtra(produto):
  if produto ['preco'] > 50:
    produto ['é caro'] = True
    return True

nova lista = filter(lambda p: p['preco'] > 10, produto)

for produto in nova_lista:
  print(produto)

from dados import produtos, pessoas, lista

def filtra(pessoa):
  if pessoa['idade'] >= 18:
    return True
  else:
    return False

nova_lista = filter(filtra, pessoas)

for pessoas in nova_lista:
  print(pessoas)