# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16fNu_uqjI9G1LsYobmZmHr5XPrbTF3pR
"""

s1 = {1,2,3,4,5,6,7,8,9,10}
print(s1)

s1 = set()
s1.update('Python')
s1.update([1,2,3,4,5,6,7,8,9,10], {11,12,13,14,15,16,17,18,19,20})
print(s1)

s1 = {1,2,3,4,5,6,7,8,9}
s2 = {1,3,5,7,9,11,13,15}
s3 = s1 ^ s2
print(s3)