# -*- coding: utf-8 -*-
"""Raise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QrCuyBjgzU6E5_0qToOjjO8THoJNpq3t
"""

def divide(n1, n2):
  if n2 == 0:
    raise ValueError ('n2 nãão pode ser 0')
  return n1 / n2

try:
  print(divide(n1=2, n2=0))
except ValueError as error:
  print('Voce estáá tentando dividir por 0')
  print('Log:', error)