# -*- coding: utf-8 -*-
"""Try except.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14WiGGPNcZvzQap4fhgTkWTKv3ybjJnvc
"""

try:
  a = "Curso python Orientado a objetos"
  print(a)
except NameError as erro:
  print('Erro do desenvolvedor, fale com ele')
except(IndexError, KeyError) as erro:
  print('Erro de indice ou chave')
except Exception as erro:
  print('Ocorreu um erro inesperado')
else:
  print('Seu código foi executado com sucesso')
  print(a)
finally:
  print('Finalmente')
print('Bora continuar')